[package]
name = "boyloader"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
uefi = { version = "0.34.1", features = ["alloc", "global_allocator", "logger", "panic_handler"] }
xmas-elf = "0.10.0"
